################################################################################
# 
# Copyright (c) 2009 ip.access Ltd.
#
#  This program is free software; you can redistribute  it and/or modify it
#  under  the terms of  the GNU General  Public License as published by the
#  Free Software Foundation;  either version 2 of the  License, or (at your
#  option) any later version.
#
#  
##############################################################################
# Filename: 
##############################################################################

obj-$(CONFIG_IPACCESS_CPETD) += cpetd/

obj-$(CONFIG_IPACCESS_CPETD) += leddriver/

obj-$(CONFIG_IPACCESS_2G) += 2g/

