################################################################################
# 
# Copyright (c) 2011 ip.access Ltd.
#
#  This program is free software; you can redistribute  it and/or modify it
#  under  the terms of  the GNU General  Public License as published by the
#  Free Software Foundation;  either version 2 of the  License, or (at your
#  option) any later version.
#
# 22 Apr 2011 Created by Simon D Hughes.
#
# Makefile for the lm75 driver
#
##############################################################################
# Filename: 
##############################################################################

obj-$(CONFIG_IPACCESS_2G) := ipa2g.o


