################################################################################
# 
# Copyright (c) 2009 ip.access Ltd.
#
#  This program is free software; you can redistribute  it and/or modify it
#  under  the terms of  the GNU General  Public License as published by the
#  Free Software Foundation;  either version 2 of the  License, or (at your
#  option) any later version.
#
# 22 Apr 2009 Created by Simon D Hughes.
##############################################################################
# Filename: 
##############################################################################
header-y += config_ipaccess.h
header-y += config_ipaccess_ip3xxff.h
header-y += cpetd.h
header-y += ipa_keystream.h
